#!/usr/bin/env bash
# -*- shell-script -*-
# Top-level program. This program may be initially invoked.
# If not running interactively, don't do anything
case $- in
  *i*) ;;
  *)   return ;;
esac

# if in a terminal
if [ -t 0 ]; then
    # other users shouldn't be able to message by default
    mesg n

    # enable colours
#    if [ `tput colors` -ge 8 ]; then
#    fi
fi


#! [check]: if `stdout` is a terminal
if [ -t 1 ] && command -v tput >/dev/null; then
  #! [check]: supports colors
  ncolors=$(tput colors || echo 0)
  if [ -n "$ncolors" ] && [ $ncolors -ge 8 ]; then
    bold="$(tput bold || echo)"
    normal="$(tput sgr0 || echo)"
    black="$(tput setaf 0 || echo)"
    red="$(tput setaf 1 || echo)"
    green="$(tput setaf 2 || echo)"
    yellow="$(tput setaf 3 || echo)"
    blue="$(tput setaf 4 || echo)"
    magenta="$(tput setaf 5 || echo)"
    cyan="$(tput setaf 6 || echo)"
    white="$(tput setaf 7 || echo)"
  fi
fi

# Local Variables:
# mode:shell-script
# sh-shell:bash
# End:
